name: Dendron

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Retain Node modules across builds
    - name: Restore Node modules cache
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: |
          node_modules
          .next/node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}-1

    - name: Install npm dependencies
      run: npm install @dendronhq/dendron-cli@latest

    - name: Initialize or pull nextjs template
      run: npx dendron publish init

    - name: Delete next cache
      run: "(test -d .next/) && (rm -rf .next/ && echo 'delete Next.js cache') || echo 'no Next.js cache found'"

    - name: Export notes
      run: npx dendron publish export --target github --yes

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true
        cname: glucknotes.com